version: "3.9"
services:
  backend:
    environment:
      OUGHT_INFERENCE_API_KEY: ${OUGHT_INFERENCE_API_KEY:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID:-}
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@database:5432/postgres
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY-}
      APP_ENV: ${APP_ENV}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${COMPOSE_BACKEND_IMAGE-ice-backend}
    volumes:
      # When mounting /code, don't clobber the .venv that's already in the container.
      # https://stackoverflow.com/a/37898591
      - /code/.venv/
      - ./:/code
    ports:
      - "8000:8000"
      - "9000:9000"
    depends_on:
      - database

  database:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
