version: "3.9"
services:
  backend:
    environment:
      OUGHT_INFERENCE_API_KEY: ${OUGHT_INFERENCE_API_KEY:-}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      OPENAI_ORG_ID: ${OPENAI_ORG_ID:-}
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY:-}
      CODESPACE_NAME: ${CODESPACE_NAME:-}
    build:
      context: .
      dockerfile: Dockerfile
    image: ${COMPOSE_BACKEND_IMAGE-ice-backend}
    volumes:
      # When mounting /code, don't clobber generated directories.
      # https://stackoverflow.com/a/37898591
      - /code/.mypy_cache
      - /code/.pre-commit-home
      - /code/.venv/
      - /code/ui/.next/
      - /code/ui/node_modules/
      - ./:/code
    ports:
      - "3000:3000"
      - "8000:8000"
      - "9000:9000"
