"""Save Node name in NodeResult

Revision ID: 6caacd5a1097
Revises: 9fb4158cadfc
Create Date: 2022-06-14 15:11:45.003460

"""
from typing import Optional

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "6caacd5a1097"
down_revision: Optional[str] = "9fb4158cadfc"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "noderesult",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.execute("UPDATE noderesult SET name = ''")
    op.alter_column("noderesult", "name", nullable=False)
    op.create_index(op.f("ix_noderesult_name"), "noderesult", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_noderesult_name"), table_name="noderesult")
    op.drop_column("noderesult", "name")
    # ### end Alembic commands ###
