"""Create NodeResult table

Revision ID: 9fb4158cadfc
Revises: a87f533e2793
Create Date: 2022-06-08 03:55:57.083311

"""
from typing import Optional

import sqlalchemy as sa
import sqlmodel

from alembic import op
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = "9fb4158cadfc"
down_revision = "a87f533e2793"
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "noderesult",
        sa.Column("inputs", JSONB(), nullable=True),
        sa.Column("result", JSONB(), nullable=True),
        sa.Column("context", JSONB(), nullable=True),
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_index("ix_completion_agent", table_name="completion")
    op.drop_index("ix_completion_document_id", table_name="completion")
    op.drop_index("ix_completion_excerpt_hash", table_name="completion")
    op.drop_index("ix_completion_mode", table_name="completion")
    op.drop_index("ix_completion_recipe_slug", table_name="completion")
    op.drop_table("completion")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "completion",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("prompt", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("completion", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("agent", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "excerpt_hash",
            sa.VARCHAR(),
            server_default=sa.text("'default'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "document_id",
            sa.VARCHAR(),
            server_default=sa.text("'default'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "question",
            sa.VARCHAR(),
            server_default=sa.text("'default'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "recipe_slug",
            sa.VARCHAR(),
            server_default=sa.text("'default'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "mode",
            sa.VARCHAR(),
            server_default=sa.text("'default'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="completion_pkey"),
    )
    op.create_index(
        "ix_completion_recipe_slug", "completion", ["recipe_slug"], unique=False
    )
    op.create_index("ix_completion_mode", "completion", ["mode"], unique=False)
    op.create_index(
        "ix_completion_excerpt_hash", "completion", ["excerpt_hash"], unique=False
    )
    op.create_index(
        "ix_completion_document_id", "completion", ["document_id"], unique=False
    )
    op.create_index("ix_completion_agent", "completion", ["agent"], unique=False)
    op.drop_table("noderesult")
    # ### end Alembic commands ###
