"""init

Revision ID: e458dd1343b4
Revises:
Create Date: 2022-05-27 21:14:12.110538

"""
from typing import Optional

import sqlalchemy as sa
import sqlmodel

from alembic import op


# revision identifiers, used by Alembic.
revision = "e458dd1343b4"
down_revision: Optional[str] = None
branch_labels: Optional[str] = None
depends_on: Optional[str] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "completion",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prompt", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("completion", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("agent", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_completion_agent"), "completion", ["agent"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_completion_agent"), table_name="completion")
    op.drop_table("completion")
    # ### end Alembic commands ###
