name: Deploy frontend to production
on:
  push:
    branches:
      - main

jobs:
  deploy-frontend-prod:
    name: Deploy production front-end on Vercel
    runs-on: ubuntu-latest

    environment:
      name: ice-prod-frontend
      url: ${{ steps.vercel-deploy.outputs.frontend_url }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
          registry-url: https://registry.npmjs.org/

      - name: Deploy on Vercel
        id: vercel-deploy
        run: |
          export FRONTEND_URL=$(npx vercel --confirm --prod --token ${{ secrets.VERCEL_TOKEN }} --scope ${{ secrets.VERCEL_TEAM_ID }} -b NEXT_PUBLIC_API_HOST=ice.fly.dev)
          echo "Deployed to Vercel at: ${FRONTEND_URL}"
          echo "::set-output name=frontend_url::${FRONTEND_URL}"
